class Estado:
    ACTIVO = 'AC'
    INACTIVO = 'IN'


class Rol:
    ADMINISTRADOR = 1
    USUARIO = 2
    CLIENTE = 3

class SizeLibro:
    MAX_FILE_SIZE = 20 * 1024 * 1024  # 20MB

class EstadoEstudiante:
    REGISTRADO = 'REGISTRADO'
    PENDIENTE_DOCUMENTO = 'PENDIENTE_DOCUMENTO'
    ACEPTADO = 'ACEPTADO'
    RECHAZADO = 'RECHAZADO'
    GRADUADO = 'GRADUADO'


class TipoDocumento:
    CEDULA = 'CEDULA'
    ACTA_NACIMIENTO = 'ACTA_NACIMIENTO'
    RECORD_ESCUELA = 'RECORD_ESCUELA'
